 const profilingData = [
        {
    "Datum der letzten Anpassung": "2025-04-01",
    "ID": "101",
    "Stelle": "Pflegefachkraft",
    "Offizielle Stellenbezeichnung": "Pflegefachkraft (m/w/d)",
    "Synonyme für Stellenbenennung": "Krankenschwester, Pfleger",
    "Akronyme für Stellenbenennung (falls üblich verwendet)": "PFK",
    "Branche": "Pflege",
    "Kurze Einleitung zur Berufsgruppe": "Pflegekräfte betreuen und versorgen Patienten.",
    "Notwendige Qualifikationen um Beruf ausüben zu können": "Pflegeausbildung,Examen",
    "Wichtige persönliche Eigenschaften & Soft Skills (Psychographic)": "Einfühlungsvermögen, Belastbarkeit",
    "Wichtige übliche demographische Eigenschaften (Demographic)": "20-50 Jahre, oft weiblich",
    "Benefits welche diese Stelle besonders anzieht beim Arbeitgeber": "Sicherer Job, gute Work-Life-Balance",
    "Karriere- und Aufstiegsmöglichkeiten": "Stationsleitung, Fachweiterbildung",
    "Spezialisierungen": "Intensivpflege, Geriatrie",
    "Durschn. Gehalt": "3500",
    "Übliche Tarifmodelle": "TVöD-P",
    "Übliche Einsatzbereiche": "Krankenhaus, Pflegeheim",
    "Übliche Arbeitszeiten & Schichtmodelle": "3-Schicht-System",
    "Besondere rechtliche oder branchenspezifische Vorgaben": "Examen erforderlich",
    "Link zu einem Stockbild was die Zielgruppe repräsentiert": "https://placehold.co/600x400",
    "Bildungsgrad 1-3": "2",
    "Durschnitt. Budget": "1200"
  },
  {
    "Datum der letzten Anpassung": "2025-04-01",
    "ID": "102",
    "Stelle": "Pflegehelfer/in",
    "Offizielle Stellenbezeichnung": "Pflegehelfer/in (m/w/d)",
    "Synonyme für Stellenbenennung": "Pflegeassistent",
    "Akronyme für Stellenbenennung (falls üblich verwendet)": "",
    "Branche": "Pflege",
    "Kurze Einleitung zur Berufsgruppe": "Unterstützt Pflegefachkräfte in der Betreuung von Patienten.",
    "Notwendige Qualifikationen um Beruf ausüben zu können": "Pflegebasiskurs",
    "Wichtige persönliche Eigenschaften & Soft Skills (Psychographic)": "Hilfsbereitschaft, Geduld",
    "Wichtige übliche demographische Eigenschaften (Demographic)": "18-50 Jahre, oft weiblich",
    "Benefits welche diese Stelle besonders anzieht beim Arbeitgeber": "Einsteigerfreundlich, flexible Arbeitszeiten",
    "Karriere- und Aufstiegsmöglichkeiten": "Ausbildung zur Pflegefachkraft",
    "Spezialisierungen": "Altenpflege, ambulante Pflege",
    "Durschn. Gehalt": "2600",
    "Übliche Tarifmodelle": "TVöD-P",
    "Übliche Einsatzbereiche": "Pflegeheim, ambulanter Dienst",
    "Übliche Arbeitszeiten & Schichtmodelle": "2-Schicht-System",
    "Besondere rechtliche oder branchenspezifische Vorgaben": "Pflegebasiskurs erforderlich",
    "Link zu einem Stockbild was die Zielgruppe repräsentiert": "https://placehold.co/600x400",
    "Bildungsgrad 1-3": "1",
    "Durschnitt. Budget": "900"
  },
  {
    "Datum der letzten Anpassung": "2025-04-01",
    "ID": "103",
    "Stelle": "Stationsleitung",
    "Offizielle Stellenbezeichnung": "Stationsleitung (m/w/d)",
    "Synonyme für Stellenbenennung": "Stationsmanager, Leitende Pflegekraft",
    "Akronyme für Stellenbenennung (falls üblich verwendet)": "",
    "Branche": "Pflege",
    "Kurze Einleitung zur Berufsgruppe": "Verantwortlich für Leitung einer Pflegeeinheit.",
    "Notwendige Qualifikationen um Beruf ausüben zu können": "Examen Pflege, Weiterbildung Leitung",
    "Wichtige persönliche Eigenschaften & Soft Skills (Psychographic)": "Organisationsfähigkeit, Führungskompetenz",
    "Wichtige übliche demographische Eigenschaften (Demographic)": "30-55 Jahre, meist weiblich",
    "Benefits welche diese Stelle besonders anzieht beim Arbeitgeber": "Karrierechance, Führungsposition",
    "Karriere- und Aufstiegsmöglichkeiten": "Pflegedienstleitung",
    "Spezialisierungen": "Personalmanagement, Qualitätsmanagement",
    "Durschn. Gehalt": "4200",
    "Übliche Tarifmodelle": "TVöD-P",
    "Übliche Einsatzbereiche": "Krankenhaus, Pflegeheim",
    "Übliche Arbeitszeiten & Schichtmodelle": "Tagschicht, gelegentliche Bereitschaft",
    "Besondere rechtliche oder branchenspezifische Vorgaben": "Weiterbildung Stationsleitung",
    "Link zu einem Stockbild was die Zielgruppe repräsentiert": "https://placehold.co/600x400",
    "Bildungsgrad 1-3": "3",
    "Durschnitt. Budget": "1400"
  },
  {
    "Datum der letzten Anpassung": "2025-04-01",
    "ID": "104",
    "Stelle": "Pflegedienstleitung (PDL)",
    "Offizielle Stellenbezeichnung": "Pflegedienstleitung (m/w/d)",
    "Synonyme für Stellenbenennung": "PDL",
    "Akronyme für Stellenbenennung (falls üblich verwendet)": "PDL",
    "Branche": "Pflege",
    "Kurze Einleitung zur Berufsgruppe": "Gesamtleitung des pflegerischen Dienstes einer Einrichtung.",
    "Notwendige Qualifikationen um Beruf ausüben zu können": "Examen Pflege, Weiterbildung Pflegedienstleitung",
    "Wichtige persönliche Eigenschaften & Soft Skills (Psychographic)": "Entscheidungsfähigkeit, Kommunikationsstärke",
    "Wichtige übliche demographische Eigenschaften (Demographic)": "35-60 Jahre, divers",
    "Benefits welche diese Stelle besonders anzieht beim Arbeitgeber": "Attraktives Gehalt, Führungsverantwortung",
    "Karriere- und Aufstiegsmöglichkeiten": "Einrichtungsleitung",
    "Spezialisierungen": "Management, Controlling",
    "Durschn. Gehalt": "5000",
    "Übliche Tarifmodelle": "TVöD-P",
    "Übliche Einsatzbereiche": "Kliniken, Pflegeheime",
    "Übliche Arbeitszeiten & Schichtmodelle": "Tagschicht, Bürozeiten",
    "Besondere rechtliche oder branchenspezifische Vorgaben": "Weiterbildung Pflegedienstleitung",
    "Link zu einem Stockbild was die Zielgruppe repräsentiert": "https://example.com/pdl.jpg",
    "Bildungsgrad 1-3": "3",
    "Durschnitt. Budget": "2000"
  },
      {
        "Datum der letzten Anpassung": "2025-04-01",
        "ID": "202",
        "Stelle": "Softwareentwickler/in",
        "Offizielle Stellenbezeichnung": "Software Developer",
        "Synonyme für Stellenbenennung": "Programmierer",
        "Akronyme für Stellenbenennung (falls üblich verwendet)": "DEV",
        "Branche": "IT",
        "Kurze Einleitung zur Berufsgruppe": "Entwickeln Softwarelösungen und Apps.",
        "Notwendige Qualifikationen um Beruf ausüben zu können": "Informatikstudium,Programmierkenntnisse",
        "Wichtige persönliche Eigenschaften & Soft Skills (Psychographic)": "Logisches Denken, Teamfähigkeit",
        "Wichtige übliche demographische Eigenschaften (Demographic)": "25-45 Jahre, divers",
        "Benefits welche diese Stelle besonders anzieht beim Arbeitgeber": "Remote-Möglichkeit, moderne Tools",
        "Karriere- und Aufstiegsmöglichkeiten": "Teamlead, CTO",
        "Spezialisierungen": "Backend, Frontend, Mobile",
        "Durschn. Gehalt": "4800",
        "Übliche Tarifmodelle": "IG Metall",
        "Übliche Einsatzbereiche": "Agentur, Konzern",
        "Übliche Arbeitszeiten & Schichtmodelle": "Gleitzeit",
        "Besondere rechtliche oder branchenspezifische Vorgaben": "Keine",
        "Link zu einem Stockbild was die Zielgruppe repräsentiert": "https://example.com/dev.jpg",
        "Bildungsgrad 1-3": "3",
        "Durschnitt. Budget": "1800"
      }
    ];
